name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main  # หรือชื่อ branch ที่คุณใช้
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # หรือเวอร์ชัน Node.js ที่คุณใช้
      - name: Install dependencies
        run: npm install -g firebase-tools
      - name: Set Firebase project
        run: |
          firebase use jrys-hub  # ตั้งค่าโปรเจกต์ที่ต้องการใช้งาน
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
          
